#!/bin/sh

#@name Generic Bi-Copter
#@type Generic Bi Copter
. ${R}etc/init.d/rc.bc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=lawn}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=Bi_Quad}

param set-default SIM_GZ_EN 1

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 0
param set-default SENS_EN_MAGSIM 1

#param set-default FD_ACT_EN 0 # Enable Actuator Failure check
param set-default CA_AIRFRAME 13
param set-default CA_METHOD 2

param set-default COM_PREARM_MODE 2 # Condition to enter prearmed mode set as Always
param set-default CA_ROTOR_COUNT 4


# Right motor
param set-default CA_ROTOR0_PX 0.0
param set-default CA_ROTOR0_PY -0.2
param set-default CA_ROTOR0_PZ 0.05
param set-default CA_ROTOR0_CT 6.5
param set-default CA_ROTOR0_KM 0.02

# Left motor
param set-default CA_ROTOR1_PX 0.0
param set-default CA_ROTOR1_PY 0.2
param set-default CA_ROTOR1_PZ 0.05
param set-default CA_ROTOR1_CT 6.5
param set-default CA_ROTOR1_KM -0.05

# Right Bottom motor
param set-default CA_ROTOR2_PX 0.0
param set-default CA_ROTOR2_PY -0.2
param set-default CA_ROTOR2_PZ 0.03
param set-default CA_ROTOR2_CT 6.5
param set-default CA_ROTOR2_KM 0.02

# Left Bottom motor
param set-default CA_ROTOR3_PX 0.0
param set-default CA_ROTOR3_PY 0.2
param set-default CA_ROTOR3_PZ 0.03
param set-default CA_ROTOR3_CT 6.5
param set-default CA_ROTOR3_KM -0.05

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_MIN1 100
param set-default SIM_GZ_EC_MAX1 900

param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_MIN2 100
param set-default SIM_GZ_EC_MAX2 900

param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_MIN3 100
param set-default SIM_GZ_EC_MAX3 900

param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_MIN4 100
param set-default SIM_GZ_EC_MAX4 900


param set-default CA_ROTOR0_TILT 2
param set-default CA_ROTOR1_TILT 1

# RC control input mode
param set-default COM_RC_IN_MODE 1

# Number of Tilt Servos
param set-default CA_SV_TL_COUNT 2

# Left servo
param set-default CA_SV_TL0_CT 3
param set-default CA_SV_TL0_MAXA 45
param set-default CA_SV_TL0_MINA -45
param set-default CA_SV_TL0_TD 0


# Right servo
param set-default CA_SV_TL1_CT 3
param set-default CA_SV_TL1_MAXA 45
param set-default CA_SV_TL1_MINA -45
param set-default CA_SV_TL1_TD 0

# Tuning Parameters
# # Rate Controller
# param set-default MC_ROLLRATE_K 1.000
# param set-default MC_ROLLRATE_D 0.0046
# param set-default MC_ROLLRATE_I 0.235

# param set-default MC_PITCHRATE_K 1.000
# param set-default MC_PITCHRATE_D 0.0124
# param set-default MC_PITCHRATE_I 0.409

# param set-default MC_YAWRATE_K 1.000
# param set-default MC_YAWRATE_I 0.20

# # Attitude Controller
# param set-default MC_ROLL_P 5.65
# param set-default MC_PITCH_P 3.13
# param set-default MC_YAW_P 4.66

# # Velocity Controller
# param set-default MPC_XY_P_ACC 3.05
# param set-default MPC_XY_I_ACC 4.60
# param set-default MPC_XY_D_ACC 1.05

# param set-default MPC_Z_P_ACC 15.00
# param set-default MPC_Z_I_ACC 3.00
# param set-default MPC_Z_D_ACC 2.00

# # Position Controller

# param set-default MPC_XY_P 0.95
# param set-default MPC_Z_P 0.90
