#!/bin/sh
#
# @name bicopter
#
# @type bicopter
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=lawn}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=bicopter}

param set-default SIM_GZ_EN 1

param set-default MAV_0_BROADCAST 1

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 0
param set-default SENS_EN_MAGSIM 1

param set-default CA_AIRFRAME 20
param set-default CA_METHOD 2

param set-default CA_ROTOR_COUNT 2
param set-default CA_ROTOR0_PX 0.0
param set-default CA_ROTOR0_PY -0.2
param set-default CA_ROTOR0_PZ 0.05
# param set-default CA_ROTOR0_CT 6.5
param set-default CA_ROTOR0_KM 0.05

param set-default CA_ROTOR1_PX 0.0
param set-default CA_ROTOR1_PY 0.2
param set-default CA_ROTOR1_PZ 0.05
# param set-default CA_ROTOR1_CT 6.5
param set-default CA_ROTOR1_KM -0.05

param set-default CA_ROTOR0_TILT 2
param set-default CA_ROTOR1_TILT 1

param set-default CA_SV_TL0_MAXA 45
param set-default CA_SV_TL0_MINA -45
param set-default CA_SV_TL0_TD 0
param set-default CA_SV_TL0_CT 3

param set-default CA_SV_TL1_MAXA 45
param set-default CA_SV_TL1_MINA -45
param set-default CA_SV_TL1_TD 0
param set-default CA_SV_TL1_CT 3

param set-default CA_SV_TL_COUNT 2

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MAX2 1000

param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202

# # Tuning Parameters
# # Rate Controller
# param set-default MC_ROLLRATE_K 1.000
# param set-default MC_ROLLRATE_D 0.0046
# param set-default MC_ROLLRATE_I 0.235

# param set-default MC_PITCHRATE_K 1.000
# param set-default MC_PITCHRATE_D 0.0124
# param set-default MC_PITCHRATE_I 0.409

param set-default MC_YAWRATE_K 0.5
param set-default MC_YAWRATE_I 0.02

# # Attitude Controller
# param set-default MC_ROLL_P 5.65
# param set-default MC_PITCH_P 3.13
param set-default MC_YAW_P 0.8

# # Position Controller

# param set-default MPC_XY_P 0.95
# param set-default MPC_Z_P 0.90
